"""
Support-level AI Platform API error simulation.

Purpose:
    This script is used for AI Platform Operations interview preparation.
    It does not call a real AI service.

    The goal is to practise how an Operations / Application Support person
    would interpret common HTTP status codes, collect evidence and decide
    when to escalate to identity, platform or DevOps teams.

What this script demonstrates:
    - Basic API support awareness
    - HTTP status code interpretation
    - Escalation thinking
    - AI Platform support scenarios
    - Support-level Python usage

What this script does NOT demonstrate:
    - Advanced Python development
    - Real Azure OpenAI administration
    - Model training
    - MLOps engineering
    - Production monitoring
"""

ERRORS = {
    200: {
        "meaning": "Request succeeded.",
        "collect": "Latency, response quality feedback if relevant.",
        "next_step": "No incident unless user reports functional issue.",
        "escalation": "None."
    },
    400: {
        "meaning": "Bad request. The input or request format may be invalid.",
        "collect": "Request body, endpoint, model deployment name, API version, timestamp.",
        "next_step": "Validate request format and required parameters.",
        "escalation": "Escalate to application or platform team if request format is generated by an application."
    },
    401: {
        "meaning": "Authentication failed. The service cannot verify the caller.",
        "collect": "Authentication method, token/API key status, timestamp, request ID.",
        "next_step": "Check credentials, token expiry or authentication configuration.",
        "escalation": "Escalate to identity/platform team if credentials or managed identity configuration must be changed."
    },
    403: {
        "meaning": "Forbidden. Caller is authenticated but does not have permission.",
        "collect": "User/app identity, group membership, RBAC, endpoint, request ID.",
        "next_step": "Compare permissions with a working user or application.",
        "escalation": "Escalate to identity/platform owner for permission review."
    },
    429: {
        "meaning": "Too many requests. Quota, rate limit or throttling issue.",
        "collect": "Request volume, affected project, timestamps, retry pattern, response headers.",
        "next_step": "Check whether usage exceeded allowed limits and whether retry/backoff is needed.",
        "escalation": "Escalate to platform owner for quota/capacity review."
    },
    500: {
        "meaning": "Server-side error.",
        "collect": "Request ID, timestamp, affected users, service health, recent deployments.",
        "next_step": "Check if issue is widespread and whether a recent deployment occurred.",
        "escalation": "Escalate to platform/DevOps team."
    },
}

for code, details in ERRORS.items():
    print(f"\n=== HTTP {code} ===")
    print(f"Meaning: {details['meaning']}")
    print(f"Collect: {details['collect']}")
    print(f"Next step: {details['next_step']}")
    print(f"Escalation: {details['escalation']}")
